---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
library(sqldf)
library(rvest)
library(lubridate)
```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
data("rest_inspec") 


  rest_inspec %>% 
  drop_na() %>% 
  mutate(
    date=as_date(grade_date)
  ) %>% 
  mutate(
    year=lubridate::year(grade_date),
    month=lubridate::month(grade_date),
    day=lubridate::day(grade_date)
  ) %>% 
  mutate(
    month = as_factor(month),
    year = as_factor(year)
  ) %>% 
  mutate(
    month = recode(month, `1`="January", `2`="February", `3`="March", `4`="April", `5`="May", `6`="June", `7`="July", `8`="August", `9`="September", `10`="October", `11`="November", `12`="December")
  ) %>% 
  group_by(month, year, violation_description) %>% 
  summarize(n=n()) %>% 
  mutate(
    percent = (n/sum(n))*100
  ) %>% 
    filter(str_detect(violation_description, "flies")) %>% 
    ungroup() %>% 
    plot_ly(x=~month, y=~percent, group=~year, type="scatter", color=~year, mode="lines+markers") %>% 
    layout(title="Percentage (%) of Violations Due to Filth Flies or Food/Refuse/Sewage-Associated Flies")


```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

data("rest_inspec") 


  rest_inspec %>% 
  drop_na() %>% 
    filter(grade=="A",
         boro %in% c("BRONX", "BROOKLYN", "MANHATTAN", "STATEN ISLAND", "QUEENS")) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box",
          colors = "Set2")%>% 
    layout(title="Distribution of Inspection Scores by Borough")

```

### Chart C

```{r}
data("rest_inspec") 

plot1=
  rest_inspec %>% 
  drop_na() %>% 
  filter(grade %in% c("A", "B", "C", "Z", "P"),
         boro %in% c("BRONX", "BROOKLYN", "MANHATTAN", "STATEN ISLAND", "QUEENS")) %>% 
    ggplot(aes(x=boro))+geom_bar(aes(fill=grade))+labs(title="Number of Restaurant Inspections by Borough", x="borough", y="number of inspections")

ggplotly(plot1)


```


